# Generated by Django 3.0.4 on 2020-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=250)),
                ('Faculty', models.CharField(max_length=250)),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('Fee', models.FloatField()),
                ('Duration', models.IntegerField()),
            ],
        ),
    ]
